### ISSUE TITLE
add icon.png

### ISSUE THREAD

**Issue by microbit-mark** [PaulDFoster/pxt-microbit-GY521#5]
To help identify the package in search

**Comment by microbit-mark** [comment]
@PaulDFoster

**Comment by microbit-mark** [comment]
Hi Paul. Polling this ticket again. Can you add an image please?

**Comment by PaulDFoster** [comment]
Please can you tell me png dimension requirements?

**Comment by microbit-mark** [comment]
16:9, 184px wide and <100Kb is best

**Comment by PaulDFoster** [comment]
icon.png added
